# Site settings
title: Jeremy Pogue
email: jeremypogue2@gmail.com
description: > # keep this and put description below
  Computer Engineering and Computer Science
url: "https://jpogue2.github.io" # the base hostname & protocol for your site
linkedin_url: "https://www.linkedin.com/in/jppogue"
github_username: jpogue2
footer_text: "This site uses <a href='https://github.com/gamingportfolio/urban-theme-portfolio'>urban-theme (portfolio)</a>."

# Build settings
markdown: kramdown
permalink: pretty
